### ISSUE TITLE
Unrecognized XML and Unrecognized XML multiline

### ISSUE THREAD

**Issue by ghost** [S1ckn3z/RemixMailHelper#1]
Remix, current version of both addon and wow.

Bugsack isn't giving much information other than

10x RemixMailHelper/RemixMailHelper.xml:17 Unrecognized XML: MultiLine
10x RemixMailHelper/RemixMailHelper.xml:32 Unrecognized XML: Text

**Comment by S1ckn3z** [comment]
Hey, sorry for the late response.
It's already fixed.
